{% set name = "dynaconf" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a28442d12860a44fad5fa1d9db918c710cbfc971e8b7694697429fb8f1c3c620

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dynaconf = dynaconf.cli:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - setuptools >=38.6.0
    - python >=3.8

test:
  imports:
    - dynaconf
  commands:
    - dynaconf --help

about:
  home: https://www.dynaconf.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Configuration Management for Python.
  doc_url: https://www.dynaconf.com/
  dev_url: https://github.com/rochacbruno/dynaconf

extra:
  recipe-maintainers:
    - carlodri
