{% set name = "dynaconf" %}
{% set version = "3.2.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8dbeef31a2343c8342c9b679772c3d005b4801c587cf2f525f98f57ec2f607f1

build:
  entry_points:
    - dynaconf=dynaconf.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=38.6.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - dynaconf
  commands:
    - pip check
    - dynaconf --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.dynaconf.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The dynamic configurator for your Python Project
  doc_url: https://www.dynaconf.com/
  dev_url: https://github.com/rochacbruno/dynaconf

extra:
  recipe-maintainers:
    - carlodri
