{% set name = "dynaconf" %}
{% set version = "3.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 74cc1897396380bb957730eb341cc0976ee9c38bbcb53d3307c50caed0aedfb8

build:
  entry_points:
    - dynaconf=dynaconf.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=38.6.0
    - pip
  run:
    - python >=3.8

test:
  imports:
    - dynaconf
  commands:
    - pip check
    - dynaconf --help
  requires:
    - pip

about:
  home: https://www.dynaconf.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The dynamic configurator for your Python Project
  doc_url: https://www.dynaconf.com/
  dev_url: https://github.com/rochacbruno/dynaconf

extra:
  recipe-maintainers:
    - carlodri
