schema_version: 1

context:
  name: dynaconf
  version: 3.2.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 4cfc6a730c533bf1a1d0bf266ae202133a22236bb3227d23eff4b8542d4034a5

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - dynaconf=dynaconf.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=38.6.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - dynaconf
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - dynaconf --help

about:
  license: MIT
  license_file: LICENSE
  summary: The dynamic configurator for your Python Project
  homepage: https://www.dynaconf.com/
  repository: https://github.com/rochacbruno/dynaconf
  documentation: https://www.dynaconf.com/

extra:
  recipe-maintainers:
    - carlodri
